export const langs = [
  'am',
  'as',
  'bn',
  'ceb',
  'el-x-koine',
  'en',
  'es',
  'es-419',
  'fa',
  'fr',
  'gof',
  'gu',
  'guq',
  'ha',
  'hbo',
  'hi',
  'hmr',
  'hr',
  'id',
  'ilo',
  'kn',
  'lo',
  'lpx',
  'lus',
  'ml',
  'mr',
  'nag',
  'ne',
  'or',
  'pa',
  'pt-br',
  'rmy-x-bsa',
  'rmy-x-vc',
  'rmy-x-vg',
  'rmy-x-vwa',
  'ru',
  'sgj',
  'shu',
  'sr-Latn',
  'sw',
  'ta',
  'tdj',
  'te',
  'tg',
  'tl',
  'tpi',
  'tr',
  'ur',
  'ur-deva',
  'vi',
];

export const owners = ['door43-catalog', 'bsa', 'unfoldingword', 'ru_gl'];

//resource, that have not manifest or others reason
export const blackListResources = [
  { owner: 'unfoldingword', name: 'BHP' },
  { owner: 'unfoldingword', name: 'en_obs-tq' },
  { owner: 'unfoldingword', name: 'en_obs-tn' },
  { owner: 'unfoldingword', name: 'en_ueb' },
  { owner: 'ru_gl', name: 'ru_rlob' },
  { owner: 'ru_gl', name: 'ru_rsob' },
  { owner: 'ru_gl', name: 'ru_obs-sn' },
  { owner: 'ru_gl', name: 'ru_twl' },
  { owner: 'door43-catalog', name: 'ru_obs' },
  { owner: 'door43-catalog', name: 'ru_obs-tn' },
  { owner: 'door43-catalog', name: 'fr_obs-tn' },
  { owner: 'door43-catalog', name: 'fr_obs-tq' },
];

/* CORE */

export const bibleSubjects = [
  'TSV Translation Notes',
  'Translation Questions',
  'TSV Translation Questions',
  'TSV Translation Words Links',
  'Bible',
  'Aligned Bible',
  'Hebrew Old Testament',
  'Greek New Testament',
  //'Translation Academy',
  //'Translation Notes',
  //'Translation Words',
];
export const obsSubjects = [
  'Open Bible Stories',
  'OBS Translation Notes',
  'OBS Translation Questions',
  'TSV OBS Translation Words Links',
  // 'TSV OBS Study Questions',
  'OBS Study Questions',
  'OBS Study Notes',
];
export const subjects = [...obsSubjects, ...bibleSubjects];
