export const bibleList = [
  {
    identifier: 'gen',
    title: 'Genesis',
    rutitle: 'Бытие',
    isset: false,
    sort: 1,
    categories: 'bible-ot',
  },
  {
    identifier: 'exo',
    title: 'Exodus',
    rutitle: 'Исход',
    isset: false,
    sort: 2,
    categories: 'bible-ot',
  },
  {
    identifier: 'lev',
    title: 'Leviticus',
    rutitle: 'Левит',
    isset: false,
    sort: 3,
    categories: 'bible-ot',
  },
  {
    identifier: 'num',
    title: 'Numbers',
    rutitle: 'Числа',
    isset: false,
    sort: 4,
    categories: 'bible-ot',
  },
  {
    identifier: 'deu',
    title: 'Deuteronomy',
    rutitle: 'Второзаконие',
    isset: false,
    sort: 5,
    categories: 'bible-ot',
  },
  {
    identifier: 'jos',
    title: 'Joshua',
    rutitle: 'Иисус Навин',
    isset: false,
    sort: 6,
    categories: 'bible-ot',
  },
  {
    identifier: 'jdg',
    title: 'Judges',
    rutitle: 'Судьи',
    isset: false,
    sort: 7,
    categories: 'bible-ot',
  },
  {
    identifier: 'rut',
    title: 'Ruth',
    rutitle: 'Руфь',
    isset: false,
    sort: 8,
    categories: 'bible-ot',
  },
  {
    identifier: '1sa',
    title: '1 Samuel',
    rutitle: '1 Царств',
    isset: false,
    sort: 9,
    categories: 'bible-ot',
  },
  {
    identifier: '2sa',
    title: '2 Samuel',
    rutitle: '2 Царств',
    isset: false,
    sort: 10,
    categories: 'bible-ot',
  },
  {
    identifier: '1ki',
    title: '1 Kings',
    rutitle: '3 Царств',
    isset: false,
    sort: 11,
    categories: 'bible-ot',
  },
  {
    identifier: '2ki',
    title: '2 Kings',
    rutitle: '4 Царств',
    isset: false,
    sort: 12,
    categories: 'bible-ot',
  },
  {
    identifier: '1ch',
    title: '1 Chronicles',
    rutitle: '1 Паралипоменон',
    isset: false,
    sort: 13,
    categories: 'bible-ot',
  },
  {
    identifier: '2ch',
    title: '2 Chronicles',
    rutitle: '2 Паралипоменон',
    isset: false,
    sort: 14,
    categories: 'bible-ot',
  },
  {
    identifier: 'ezr',
    title: 'Ezra',
    rutitle: 'Ездры',
    isset: false,
    sort: 15,
    categories: 'bible-ot',
  },
  {
    identifier: 'neh',
    title: 'Nehemiah',
    rutitle: 'Неемии',
    isset: false,
    sort: 16,
    categories: 'bible-ot',
  },
  {
    identifier: 'est',
    title: 'Esther',
    rutitle: 'Есфирь',
    isset: false,
    sort: 17,
    categories: 'bible-ot',
  },
  {
    identifier: 'job',
    title: 'Job',
    rutitle: 'Иов',
    isset: false,
    sort: 18,
    categories: 'bible-ot',
  },
  {
    identifier: 'psa',
    title: 'Psalms',
    rutitle: 'Псалтырь',
    isset: false,
    sort: 19,
    categories: 'bible-ot',
  },
  {
    identifier: 'pro',
    title: 'Proverbs',
    rutitle: 'Притчи',
    isset: false,
    sort: 20,
    categories: 'bible-ot',
  },
  {
    identifier: 'ecc',
    title: 'Ecclesiastes',
    rutitle: 'Екклесиаст',
    isset: false,
    sort: 21,
    categories: 'bible-ot',
  },
  {
    identifier: 'sng',
    title: 'Song of Solomon',
    rutitle: 'Песнь Песней',
    isset: false,
    sort: 22,
    categories: 'bible-ot',
  },
  {
    identifier: 'isa',
    title: 'Isaiah',
    rutitle: 'Исайя',
    isset: false,
    sort: 23,
    categories: 'bible-ot',
  },
  {
    identifier: 'jer',
    title: 'Jeremiah',
    rutitle: 'Иеремия',
    isset: false,
    sort: 24,
    categories: 'bible-ot',
  },
  {
    identifier: 'lam',
    title: 'Lamentations',
    rutitle: 'Плач Иеремии',
    isset: false,
    sort: 25,
    categories: 'bible-ot',
  },
  {
    identifier: 'ezk',
    title: 'Ezekiel',
    rutitle: 'Иезекиль',
    isset: false,
    sort: 26,
    categories: 'bible-ot',
  },
  {
    identifier: 'dan',
    title: 'Daniel',
    rutitle: 'Даниил',
    isset: false,
    sort: 27,
    categories: 'bible-ot',
  },
  {
    identifier: 'hos',
    title: 'Hosea',
    rutitle: 'Осия',
    isset: false,
    sort: 28,
    categories: 'bible-ot',
  },
  {
    identifier: 'jol',
    title: 'Joel',
    rutitle: 'Иоиль',
    isset: false,
    sort: 29,
    categories: 'bible-ot',
  },
  {
    identifier: 'amo',
    title: 'Amos',
    rutitle: 'Амос',
    isset: false,
    sort: 30,
    categories: 'bible-ot',
  },
  {
    identifier: 'oba',
    title: 'Obadiah',
    rutitle: 'Авдий',
    isset: false,
    sort: 31,
    categories: 'bible-ot',
  },
  {
    identifier: 'jon',
    title: 'Jonah',
    rutitle: 'Иона',
    isset: false,
    sort: 32,
    categories: 'bible-ot',
  },
  {
    identifier: 'mic',
    title: 'Micah',
    rutitle: 'Михей',
    isset: false,
    sort: 33,
    categories: 'bible-ot',
  },
  {
    identifier: 'nam',
    title: 'Nahum',
    rutitle: 'Наум',
    isset: false,
    sort: 34,
    categories: 'bible-ot',
  },
  {
    identifier: 'hab',
    title: 'Habakkuk',
    rutitle: 'Аввакум',
    isset: false,
    sort: 35,
    categories: 'bible-ot',
  },
  {
    identifier: 'zep',
    title: 'Zephaniah',
    rutitle: 'Софония',
    isset: false,
    sort: 36,
    categories: 'bible-ot',
  },
  {
    identifier: 'hag',
    title: 'Haggai',
    rutitle: 'Аггей',
    isset: false,
    sort: 37,
    categories: 'bible-ot',
  },
  {
    identifier: 'zec',
    title: 'Zechariah',
    rutitle: 'Захария',
    isset: false,
    sort: 38,
    categories: 'bible-ot',
  },
  {
    identifier: 'mal',
    title: 'Malachi',
    rutitle: 'Малахия',
    isset: false,
    sort: 39,
    categories: 'bible-ot',
  },
  {
    identifier: 'mat',
    title: 'Matthew',
    rutitle: 'Матфей',
    isset: false,
    sort: 40,
    categories: 'bible-nt',
  },
  {
    identifier: 'mrk',
    title: 'Mark',
    rutitle: 'Марк',
    isset: false,
    sort: 41,
    categories: 'bible-nt',
  },
  {
    identifier: 'luk',
    title: 'Luke',
    rutitle: 'Лука',
    isset: false,
    sort: 42,
    categories: 'bible-nt',
  },
  {
    identifier: 'jhn',
    title: 'John',
    rutitle: 'Иоанн',
    isset: false,
    sort: 43,
    categories: 'bible-nt',
  },
  {
    identifier: 'act',
    title: 'Acts',
    rutitle: 'Деяния',
    isset: false,
    sort: 44,
    categories: 'bible-nt',
  },
  {
    identifier: 'rom',
    title: 'Romans',
    rutitle: 'Римлянам',
    isset: false,
    sort: 45,
    categories: 'bible-nt',
  },
  {
    identifier: '1co',
    title: '1 Corinthians',
    rutitle: '1 Коринфянам',
    isset: false,
    sort: 46,
    categories: 'bible-nt',
  },
  {
    identifier: '2co',
    title: '2 Corinthians',
    rutitle: '2 Коринфянам',
    isset: false,
    sort: 47,
    categories: 'bible-nt',
  },
  {
    identifier: 'gal',
    title: 'Galatians',
    rutitle: 'Галатам',
    isset: false,
    sort: 48,
    categories: 'bible-nt',
  },
  {
    identifier: 'eph',
    title: 'Ephesians',
    rutitle: 'Ефесянам',
    isset: false,
    sort: 49,
    categories: 'bible-nt',
  },
  {
    identifier: 'php',
    title: 'Philippians',
    rutitle: 'Филлипийцам',
    isset: false,
    sort: 50,
    categories: 'bible-nt',
  },
  {
    identifier: 'col',
    title: 'Colossians',
    rutitle: 'Колоссянам',
    isset: false,
    sort: 51,
    categories: 'bible-nt',
  },
  {
    identifier: '1th',
    title: '1 Thessalonians',
    rutitle: '1 Фессалоникийцам',
    isset: false,
    sort: 52,
    categories: 'bible-nt',
  },
  {
    identifier: '2th',
    title: '2 Thessalonians',
    rutitle: '2 Фессалоникийцам',
    isset: false,
    sort: 53,
    categories: 'bible-nt',
  },
  {
    identifier: '1ti',
    title: '1 Timothy',
    rutitle: '1 Тимофею',
    isset: false,
    sort: 54,
    categories: 'bible-nt',
  },
  {
    identifier: '2ti',
    title: '2 Timothy',
    rutitle: '2 Тимофею',
    isset: false,
    sort: 55,
    categories: 'bible-nt',
  },
  {
    identifier: 'tit',
    title: 'Titus',
    rutitle: 'Титу',
    isset: false,
    sort: 56,
    categories: 'bible-nt',
  },
  {
    identifier: 'phm',
    title: 'Philemon',
    rutitle: 'Филимону',
    isset: false,
    sort: 57,
    categories: 'bible-nt',
  },
  {
    identifier: 'heb',
    title: 'Hebrews',
    rutitle: 'Евреям',
    isset: false,
    sort: 58,
    categories: 'bible-nt',
  },
  {
    identifier: 'jas',
    title: 'James',
    rutitle: 'Послание Иакова',
    isset: false,
    sort: 59,
    categories: 'bible-nt',
  },
  {
    identifier: '1pe',
    title: '1 Peter',
    rutitle: '1 Петра',
    isset: false,
    sort: 60,
    categories: 'bible-nt',
  },
  {
    identifier: '2pe',
    title: '2 Peter',
    rutitle: '2 Петра',
    isset: false,
    sort: 61,
    categories: 'bible-nt',
  },
  {
    identifier: '1jn',
    title: '1 John',
    rutitle: '1 Иоанна',
    isset: false,
    sort: 62,
    categories: 'bible-nt',
  },
  {
    identifier: '2jn',
    title: '2 John',
    rutitle: '2 Иоанна',
    isset: false,
    sort: 63,
    categories: 'bible-nt',
  },
  {
    identifier: '3jn',
    title: '3 John',
    rutitle: '3 Иоанна',
    isset: false,
    sort: 64,
    categories: 'bible-nt',
  },
  {
    identifier: 'jud',
    title: 'Jude',
    rutitle: 'Послание Иуды',
    isset: false,
    sort: 65,
    categories: 'bible-nt',
  },
  {
    identifier: 'rev',
    title: 'Revelation',
    rutitle: 'Откровение Иоанна Богослова',
    isset: false,
    sort: 66,
    categories: 'bible-nt',
  },
];

export const resourcesList = {
  rob: {
    link: 'bsa/ru_rob/master',
    branch: 'master',
    type: 'bible',
    languageId: 'ru',
    resourceId: 'rob',
    title: 'Russian Open Bible',
    owner: 'bsa',
  },
  rlob: {
    link: 'bsa/ru_rlob/master',
    branch: 'master',
    type: 'bible',
    languageId: 'ru',
    resourceId: 'rlob',
    title: 'Russian Literal Open Bible',
    owner: 'bsa',
  },
  rsob: {
    link: 'bsa/ru_rsob/master',
    branch: 'master',
    type: 'bible',
    languageId: 'ru',
    resourceId: 'rsob',
    title: 'Russian Simplified Open Bible',
    owner: 'bsa',
  },
  ugnt: {
    link: 'unfoldingWord/el-x-koine_ugnt/master',
    branch: 'master',
    type: 'bible',
    languageId: 'el-x-koine',
    resourceId: 'ugnt',
    title: 'unfoldingWord® Greek New Testament',
    owner: 'unfoldingWord',
  },
  uhb: {
    link: 'unfoldingWord/hbo_uhb/master',
    branch: 'master',
    type: 'bible',
    languageId: 'hbo',
    resourceId: 'uhb',
    title: 'unfoldingWord® Hebrew Bible',
    owner: 'unfoldingWord',
  },
  ult: {
    link: 'unfoldingWord/en_ult/master',
    branch: 'master',
    type: 'bible',
    languageId: 'en',
    resourceId: 'ult',
    title: 'unfoldingWord® Literal Text',
    owner: 'unfoldingWord',
  },
  ust: {
    link: 'unfoldingWord/en_ust/master',
    branch: 'master',
    type: 'bible',
    languageId: 'en',
    resourceId: 'ust',
    title: 'unfoldingWord® Literal Text',
    owner: 'unfoldingWord',
  },
  tn: {
    link: 'bsa/ru_tn/master',
    branch: 'master',
    type: 'support',
    languageId: 'ru',
    resourceId: 'tn',
    title: 'Translation Notes',
    owner: 'bsa',
  },
  tq: {
    link: 'bsa/ru_tq/master',
    branch: 'master',
    type: 'support',
    languageId: 'ru',
    resourceId: 'tq',
    title: 'Translation Questions',
    owner: 'bsa',
  },
  /*ta: {
    link: 'bsa/ru_ta/master',
    branch: 'master',
    type: 'support',
    languageId: 'ru',
    resourceId: 'ta',
    title: 'ta',
    owner: 'bsa',
  },
  tw: {
    link: 'bsa/ru_tw/master',
    branch: 'master',
    type: 'support',
    languageId: 'ru',
    resourceId: 'tw',
    title: 'tw',
    owner: 'bsa',
  },*/
};
