export const bibleList = [
  {
    identifier: 'gen',
    isset: false,
    sort: 1,
    categories: 'bible-ot',
  },
  {
    identifier: 'exo',
    isset: false,
    sort: 2,
    categories: 'bible-ot',
  },
  {
    identifier: 'lev',
    isset: false,
    sort: 3,
    categories: 'bible-ot',
  },
  {
    identifier: 'num',
    isset: false,
    sort: 4,
    categories: 'bible-ot',
  },
  {
    identifier: 'deu',
    isset: false,
    sort: 5,
    categories: 'bible-ot',
  },
  {
    identifier: 'jos',
    isset: false,
    sort: 6,
    categories: 'bible-ot',
  },
  {
    identifier: 'jdg',
    isset: false,
    sort: 7,
    categories: 'bible-ot',
  },
  {
    identifier: 'rut',
    isset: false,
    sort: 8,
    categories: 'bible-ot',
  },
  {
    identifier: '1sa',
    isset: false,
    sort: 9,
    categories: 'bible-ot',
  },
  {
    identifier: '2sa',
    isset: false,
    sort: 10,
    categories: 'bible-ot',
  },
  {
    identifier: '1ki',
    isset: false,
    sort: 11,
    categories: 'bible-ot',
  },
  {
    identifier: '2ki',
    isset: false,
    sort: 12,
    categories: 'bible-ot',
  },
  {
    identifier: '1ch',
    isset: false,
    sort: 13,
    categories: 'bible-ot',
  },
  {
    identifier: '2ch',
    isset: false,
    sort: 14,
    categories: 'bible-ot',
  },
  {
    identifier: 'ezr',
    isset: false,
    sort: 15,
    categories: 'bible-ot',
  },
  {
    identifier: 'neh',
    isset: false,
    sort: 16,
    categories: 'bible-ot',
  },
  {
    identifier: 'est',
    isset: false,
    sort: 17,
    categories: 'bible-ot',
  },
  {
    identifier: 'job',
    isset: false,
    sort: 18,
    categories: 'bible-ot',
  },
  {
    identifier: 'psa',
    isset: false,
    sort: 19,
    categories: 'bible-ot',
  },
  {
    identifier: 'pro',
    isset: false,
    sort: 20,
    categories: 'bible-ot',
  },
  {
    identifier: 'ecc',
    isset: false,
    sort: 21,
    categories: 'bible-ot',
  },
  {
    identifier: 'sng',
    isset: false,
    sort: 22,
    categories: 'bible-ot',
  },
  {
    identifier: 'isa',
    isset: false,
    sort: 23,
    categories: 'bible-ot',
  },
  {
    identifier: 'jer',
    isset: false,
    sort: 24,
    categories: 'bible-ot',
  },
  {
    identifier: 'lam',
    isset: false,
    sort: 25,
    categories: 'bible-ot',
  },
  {
    identifier: 'ezk',
    isset: false,
    sort: 26,
    categories: 'bible-ot',
  },
  {
    identifier: 'dan',
    isset: false,
    sort: 27,
    categories: 'bible-ot',
  },
  {
    identifier: 'hos',
    isset: false,
    sort: 28,
    categories: 'bible-ot',
  },
  {
    identifier: 'jol',
    isset: false,
    sort: 29,
    categories: 'bible-ot',
  },
  {
    identifier: 'amo',
    isset: false,
    sort: 30,
    categories: 'bible-ot',
  },
  {
    identifier: 'oba',
    isset: false,
    sort: 31,
    categories: 'bible-ot',
  },
  {
    identifier: 'jon',
    isset: false,
    sort: 32,
    categories: 'bible-ot',
  },
  {
    identifier: 'mic',
    isset: false,
    sort: 33,
    categories: 'bible-ot',
  },
  {
    identifier: 'nam',
    isset: false,
    sort: 34,
    categories: 'bible-ot',
  },
  {
    identifier: 'hab',
    isset: false,
    sort: 35,
    categories: 'bible-ot',
  },
  {
    identifier: 'zep',
    isset: false,
    sort: 36,
    categories: 'bible-ot',
  },
  {
    identifier: 'hag',
    isset: false,
    sort: 37,
    categories: 'bible-ot',
  },
  {
    identifier: 'zec',
    isset: false,
    sort: 38,
    categories: 'bible-ot',
  },
  {
    identifier: 'mal',
    isset: false,
    sort: 39,
    categories: 'bible-ot',
  },
  {
    identifier: 'mat',
    isset: false,
    sort: 40,
    categories: 'bible-nt',
  },
  {
    identifier: 'mrk',
    isset: false,
    sort: 41,
    categories: 'bible-nt',
  },
  {
    identifier: 'luk',
    isset: false,
    sort: 42,
    categories: 'bible-nt',
  },
  {
    identifier: 'jhn',
    isset: false,
    sort: 43,
    categories: 'bible-nt',
  },
  {
    identifier: 'act',
    isset: false,
    sort: 44,
    categories: 'bible-nt',
  },
  {
    identifier: 'rom',
    isset: false,
    sort: 45,
    categories: 'bible-nt',
  },
  {
    identifier: '1co',
    isset: false,
    sort: 46,
    categories: 'bible-nt',
  },
  {
    identifier: '2co',
    isset: false,
    sort: 47,
    categories: 'bible-nt',
  },
  {
    identifier: 'gal',
    isset: false,
    sort: 48,
    categories: 'bible-nt',
  },
  {
    identifier: 'eph',
    isset: false,
    sort: 49,
    categories: 'bible-nt',
  },
  {
    identifier: 'php',
    isset: false,
    sort: 50,
    categories: 'bible-nt',
  },
  {
    identifier: 'col',
    isset: false,
    sort: 51,
    categories: 'bible-nt',
  },
  {
    identifier: '1th',
    isset: false,
    sort: 52,
    categories: 'bible-nt',
  },
  {
    identifier: '2th',
    isset: false,
    sort: 53,
    categories: 'bible-nt',
  },
  {
    identifier: '1ti',
    isset: false,
    sort: 54,
    categories: 'bible-nt',
  },
  {
    identifier: '2ti',
    isset: false,
    sort: 55,
    categories: 'bible-nt',
  },
  {
    identifier: 'tit',
    isset: false,
    sort: 56,
    categories: 'bible-nt',
  },
  {
    identifier: 'phm',
    isset: false,
    sort: 57,
    categories: 'bible-nt',
  },
  {
    identifier: 'heb',
    isset: false,
    sort: 58,
    categories: 'bible-nt',
  },
  {
    identifier: 'jas',
    isset: false,
    sort: 59,
    categories: 'bible-nt',
  },
  {
    identifier: '1pe',
    isset: false,
    sort: 60,
    categories: 'bible-nt',
  },
  {
    identifier: '2pe',
    isset: false,
    sort: 61,
    categories: 'bible-nt',
  },
  {
    identifier: '1jn',
    isset: false,
    sort: 62,
    categories: 'bible-nt',
  },
  {
    identifier: '2jn',
    isset: false,
    sort: 63,
    categories: 'bible-nt',
  },
  {
    identifier: '3jn',
    isset: false,
    sort: 64,
    categories: 'bible-nt',
  },
  {
    identifier: 'jud',
    isset: false,
    sort: 65,
    categories: 'bible-nt',
  },
  {
    identifier: 'rev',
    isset: false,
    sort: 66,
    categories: 'bible-nt',
  },
];

export const resourcesList = {
  rob: {
    link: 'bsa/ru_rob/master',
    branch: 'master',
    type: 'bible',
    languageId: 'ru',
    resourceId: 'rob',
    title: 'Russian Open Bible',
    owner: 'bsa',
  },
  rlob: {
    link: 'bsa/ru_rlob/master',
    branch: 'master',
    type: 'bible',
    languageId: 'ru',
    resourceId: 'rlob',
    title: 'Russian Literal Open Bible',
    owner: 'bsa',
  },
  rsob: {
    link: 'bsa/ru_rsob/master',
    branch: 'master',
    type: 'bible',
    languageId: 'ru',
    resourceId: 'rsob',
    title: 'Russian Simplified Open Bible',
    owner: 'bsa',
  },
  ugnt: {
    link: 'unfoldingWord/el-x-koine_ugnt/master',
    branch: 'master',
    type: 'bible',
    languageId: 'el-x-koine',
    resourceId: 'ugnt',
    title: 'unfoldingWord® Greek New Testament',
    owner: 'unfoldingWord',
  },
  uhb: {
    link: 'unfoldingWord/hbo_uhb/master',
    branch: 'master',
    type: 'bible',
    languageId: 'hbo',
    resourceId: 'uhb',
    title: 'unfoldingWord® Hebrew Bible',
    owner: 'unfoldingWord',
  },
  ult: {
    link: 'unfoldingWord/en_ult/master',
    branch: 'master',
    type: 'bible',
    languageId: 'en',
    resourceId: 'ult',
    title: 'unfoldingWord® Literal Text',
    owner: 'unfoldingWord',
  },
  ust: {
    link: 'unfoldingWord/en_ust/master',
    branch: 'master',
    type: 'bible',
    languageId: 'en',
    resourceId: 'ust',
    title: 'unfoldingWord® Literal Text',
    owner: 'unfoldingWord',
  },
  tn: {
    link: 'bsa/ru_tn/master',
    branch: 'master',
    type: 'support',
    languageId: 'ru',
    resourceId: 'tn',
    title: 'Translation Notes',
    owner: 'bsa',
  },
  tq: {
    link: 'bsa/ru_tq/master',
    branch: 'master',
    type: 'support',
    languageId: 'ru',
    resourceId: 'tq',
    title: 'Translation Questions',
    owner: 'bsa',
  },
  /*ta: {
    link: 'bsa/ru_ta/master',
    branch: 'master',
    type: 'support',
    languageId: 'ru',
    resourceId: 'ta',
    title: 'ta',
    owner: 'bsa',
  },
  tw: {
    link: 'bsa/ru_tw/master',
    branch: 'master',
    type: 'support',
    languageId: 'ru',
    resourceId: 'tw',
    title: 'tw',
    owner: 'bsa',
  },*/
};
